### ISSUE TITLE
修改音频文件名后报错

### ISSUE THREAD

**Issue by HXS572** [yeyupiaoling/SpeechEmotionRecognition-PaddlePaddle#1]
index = magnitudes[:, 1].argmax()
IndexError: index 1 is out of bounds for axis 1 with size 1

我把音频文件名改成了300_12_32.wav的格式之后，就报了错，想知道原因是什么？求解

**Comment by yeyupiaoling** [comment]
这个错误跟名字无关吧，具体什么错误，更多的错误信息看看

**Comment by HXS572** [comment]
小白一个，弄了好久都没弄好，可以帮我看一下吗，全部的报错信息，如下：
D:\ProgramData\Anaconda3\envs\ser37\python.exe E:/code/SpeechEmotionRecognition-PaddlePaddle-master/create_data.py
  2%|▏         | 132/5890 [00:15<11:13,  8.55it/s]
Traceback (most recent call last):
  File "E:/code/SpeechEmotionRecognition-PaddlePaddle-master/create_data.py", line 47, in <module>
    create_standard('dataset', 'dataset/standard.m')
  File "E:/code/SpeechEmotionRecognition-PaddlePaddle-master/create_data.py", line 40, in create_standard
    data.append(load_audio(path, mode='infer'))
  File "E:\code\SpeechEmotionRecognition-PaddlePaddle-master\data_utils\reader.py", line 46, in load_audio
    features = audio_features(X=wav, sample_rate=sr)
  File "E:\code\SpeechEmotionRecognition-PaddlePaddle-master\data_utils\utils.py", line 12, in audio_features
    index = magnitudes[:, 1].argmax()
IndexError: index 1 is out of bounds for axis 1 with size 1

Process finished with exit code 1

**Comment by yeyupiaoling** [comment]
这个我看不出是什么问题，极有可能是音频有问题。

**Comment by HXS572** [comment]
嗯嗯好，谢谢，我试试换别的音频看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeyupiaoling/SpeechEmotionRecognition-PaddlePaddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月26日(星期天) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yeyupiaoling/SpeechEmotionRecognition-PaddlePaddle] 修改音频文件名后报错 (Issue #1)





 
这个我看不出是什么问题，极有可能是音频有问题。
